_wandb:
    value:
        cli_version: 0.23.1
        e:
            nevk6q7ayouf8ta87hojg4syx47eget0:
                codePath: c:\Users\Adrian Ojeda\Desktop\ulpgc\TERCER_CURSO\AA2\red_convolutiva\modelo_tradicional.ipynb
                codePathLocal: modelo_tradicional.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "499165163520"
                        used: "154786508800"
                email: adriojeda04@gmail.com
                executable: c:\Python313\python.exe
                git:
                    commit: 4576bd05caf5fb431cdf6bef4e6a9e3ea45888dc
                    remote: https://github.com/adriaanojeda/red_convolutiva.git
                gpu: NVIDIA GeForce GTX 1660
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1408
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce GTX 1660
                      uuid: GPU-be6cbd79-d8bd-fdde-85a0-c690c1e42a74
                host: DESKTOP-KVD0NI9
                memory:
                    total: "34309693440"
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\Adrian Ojeda\Desktop\ulpgc\TERCER_CURSO\AA2\red_convolutiva\modelo_tradicional.ipynb
                python: CPython 3.13.1
                root: c:\Users\Adrian Ojeda\Desktop\ulpgc\TERCER_CURSO\AA2\red_convolutiva
                startedAt: "2025-12-05T23:10:55.063194Z"
                writerId: nevk6q7ayouf8ta87hojg4syx47eget0
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 16
            "4": 3.13.1
            "5": 0.23.1
            "8":
                - 1
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 30
lr:
    value: 0.001
model:
    value: Custom_CNN_4Layers
strategy:
    value: Training from Scratch
