_wandb:
    value:
        cli_version: 0.23.1
        e:
            nl9aq6jiktml5jx051gq5h7p4kidqs5p:
                codePath: c:\Users\Adrian Ojeda\Desktop\ulpgc\TERCER_CURSO\AA2\red_convolutiva\red_convolutiva.ipynb
                codePathLocal: red_convolutiva.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "499165163520"
                        used: "153572700160"
                email: adriojeda04@gmail.com
                executable: c:\Python313\python.exe
                git:
                    remote: https://github.com/adriaanojeda/red_convolutiva.git
                gpu: NVIDIA GeForce GTX 1660
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1408
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce GTX 1660
                      uuid: GPU-be6cbd79-d8bd-fdde-85a0-c690c1e42a74
                host: DESKTOP-KVD0NI9
                memory:
                    total: "34309693440"
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\Adrian Ojeda\Desktop\ulpgc\TERCER_CURSO\AA2\red_convolutiva\red_convolutiva.ipynb
                python: CPython 3.13.1
                root: c:\Users\Adrian Ojeda\Desktop\ulpgc\TERCER_CURSO\AA2\red_convolutiva
                startedAt: "2025-12-05T20:05:05.318572Z"
                writerId: nl9aq6jiktml5jx051gq5h7p4kidqs5p
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 16
            "4": 3.13.1
            "5": 0.23.1
            "8":
                - 1
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 20
lr_features:
    value: 1e-05
lr_head:
    value: 0.0001
model:
    value: ResNet50
strategy:
    value: Deep Fine-Tuning (Layer4)
